### ISSUE TITLE
OOM issue when using getLinkedNotebooks.

### ISSUE THREAD

**Issue by LionYang** [evernote/evernote-sdk-android#46]
java.lang.OutOfMemoryError
	at com.evernote.thrift.protocol.TBinaryProtocol.readStringBody(int)
	at com.evernote.thrift.protocol.TBinaryProtocol.readString()
	at com.evernote.thrift.protocol.TBinaryProtocol.readMessageBegin()
	at com.evernote.edam.notestore.NoteStore$Client.recv_listLinkedNotebooks()
	at myapp.evernote.logic.EvernoteApi.getLinkedNoteBooks()
	at myapp.evernote.logic.EvernoteApi.listLinkedNotebooks(FileData)
	at myapp.evernote.logic.EvernoteApi.replace(org.w3c.dom.Document,java.lang.String,java.lang.String), 
	at myapp.evernote.logic.EvernoteCache$1.doInBackground$10299ca()
	at myapp.evernote.logic.EvernoteCache$1.doInBackground(java.lang.Object[])
	at java.lang.Thread.run(Thread.java:838)

**Comment by vRallev** [comment]
Please update the SDK. There is a new version 2.0.0 which should fix the issue.
